// Generic placeholder demo catalog. Replace with the client's own menu during onboarding.
export const AEON_CATALOG_SEED = [
  {"id":"menu_demo_tea","name":"Tea","price":150,"category":"drink","module_type":"dining","in_stock":1,"image_url":"/images/menu/tea.svg","ingredients":"Black tea, hot water","calories":2,"protein":0,"carbs":0.5,"fat":0},
  {"id":"menu_demo_filter_coffee","name":"Filter Coffee","price":400,"category":"drink","module_type":"dining","in_stock":1,"image_url":"/images/menu/filter-coffee.svg","ingredients":"Arabica coffee, hot water","calories":5,"protein":0.3,"carbs":0.8,"fat":0.1},
  {"id":"menu_demo_cappuccino","name":"Cappuccino","price":300,"category":"drink","module_type":"dining","in_stock":1,"image_url":"/images/menu/cappuccino.svg","ingredients":"Espresso, steamed milk, foam","calories":120,"protein":6.0,"carbs":9.0,"fat":6.5},
  {"id":"menu_demo_fresh_orange_juice","name":"Fresh Orange Juice","price":350,"category":"drink","module_type":"dining","in_stock":1,"image_url":"/images/menu/fresh-orange-juice.svg","ingredients":"Fresh squeezed oranges","calories":110,"protein":1.8,"carbs":25.0,"fat":0.3},
  {"id":"menu_demo_soft_drink","name":"Soft Drink","price":200,"category":"drink","module_type":"dining","in_stock":1,"image_url":"/images/menu/soft-drink.svg","ingredients":"Carbonated soft drink","calories":140,"protein":0,"carbs":35.0,"fat":0},
  {"id":"menu_demo_water","name":"Water 0.5L","price":100,"category":"drink","module_type":"dining","in_stock":1,"image_url":"/images/menu/water-05l.svg","ingredients":"Natural spring water","calories":0,"protein":0,"carbs":0,"fat":0},
  {"id":"menu_demo_garden_salad","name":"Garden Salad","price":600,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/garden-salad.svg","ingredients":"Tomato, cucumber, onion, olive oil, lemon","calories":160,"protein":3.0,"carbs":12.0,"fat":11.0},
  {"id":"menu_demo_caesar_salad","name":"Caesar Salad","price":700,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/caesar-salad.svg","ingredients":"Romaine lettuce, parmesan, croutons, caesar dressing","calories":320,"protein":9.0,"carbs":14.0,"fat":24.0},
  {"id":"menu_demo_grilled_chicken","name":"Grilled Chicken","price":1200,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/grilled-chicken.svg","ingredients":"Chicken breast, herbs, olive oil","calories":420,"protein":45.0,"carbs":2.0,"fat":22.0},
  {"id":"menu_demo_grilled_seabass","name":"Grilled Seabass","price":1600,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/grilled-seabass.svg","ingredients":"Seabass fillet, lemon, herbs","calories":380,"protein":40.0,"carbs":0,"fat":20.0},
  {"id":"menu_demo_beef_burger","name":"Beef Burger","price":950,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/beef-burger.svg","ingredients":"Beef patty, bun, lettuce, tomato, cheese","calories":650,"protein":32.0,"carbs":40.0,"fat":36.0},
  {"id":"menu_demo_margherita_pizza","name":"Margherita Pizza","price":850,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/margherita-pizza.svg","ingredients":"Tomato sauce, mozzarella, basil","calories":700,"protein":24.0,"carbs":80.0,"fat":28.0},
  {"id":"menu_demo_tiramisu","name":"Tiramisu","price":700,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/tiramisu.svg","ingredients":"Mascarpone, ladyfingers, espresso, cocoa","calories":380,"protein":7.5,"carbs":42.0,"fat":20.0},
  {"id":"menu_demo_cheesecake","name":"Cheesecake","price":700,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/cheesecake.svg","ingredients":"Cream cheese, biscuit base, berry sauce","calories":420,"protein":6.8,"carbs":45.0,"fat":24.0},
  {"id":"menu_demo_fruit_plate","name":"Fruit Plate","price":750,"category":"food","module_type":"dining","in_stock":1,"image_url":"/images/menu/fruit-plate.svg","ingredients":"Seasonal fresh fruit","calories":180,"protein":2.5,"carbs":44.0,"fat":0.8}
];
