import { id, actor, audit, today, json, parse, mask } from './helpers.js';

// Reception task board, KBS identity notification tracking, cash-shift open/close,
// night audit, reporting, and the audit-event log viewer.
export function registerOperationsRoutes({ app }) {
  app.get('/api/reception/tasks', async (req, res) => res.json(await req.db.all("SELECT t.*, r.room_number FROM reception_tasks t LEFT JOIN rooms r ON r.id = t.room_id WHERE t.status <> 'completed' ORDER BY t.created_at DESC")));
  app.post('/api/reception/tasks', async (req, res) => { const data = req.body || {}; if (!data.task_type || !data.department) return res.status(400).json({ error: 'Görev türü ve departman zorunludur.' }); const user = actor(req); const taskId = id('task'); await req.db.run('INSERT INTO reception_tasks (id, task_type, department, room_id, stay_id, priority, due_at, details, created_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [taskId, data.task_type, data.department, data.room_id || null, data.stay_id || null, data.priority || 'normal', data.due_at || null, data.details || null, user.name]); await audit(req.db, req, 'task', taskId, 'created', null, data); res.status(201).json({ id: taskId }); });
  app.patch('/api/reception/tasks/:id', async (req, res) => { const task = await req.db.get('SELECT * FROM reception_tasks WHERE id = ?', [req.params.id]); if (!task) return res.status(404).json({ error: 'Görev bulunamadı.' }); const user = actor(req); await req.db.run('UPDATE reception_tasks SET status = ?, completed_at = ?, completed_by = ? WHERE id = ?', [req.body.status || task.status, req.body.status === 'completed' ? new Date().toISOString() : null, req.body.status === 'completed' ? user.name : null, task.id]); await audit(req.db, req, 'task', task.id, 'updated', task, req.body); res.json({ success: true }); });
  app.get('/api/reception/kbs', async (req, res) => { const rows = await req.db.all('SELECT n.*, g.first_name, g.last_name, g.identity_number, g.passport_number FROM identity_notifications n JOIN guest_profiles g ON g.id = n.guest_id ORDER BY n.created_at DESC'); res.json(rows.map(item => ({ ...item, identity_number: mask(item.identity_number), passport_number: mask(item.passport_number) }))); });
  app.patch('/api/reception/kbs/:id', async (req, res) => { const item = await req.db.get('SELECT * FROM identity_notifications WHERE id = ?', [req.params.id]); if (!item) return res.status(404).json({ error: 'Bildirim bulunamadı.' }); const status = req.body.status; if (!['pending', 'submitted', 'accepted', 'rejected', 'manual_review'].includes(status)) return res.status(400).json({ error: 'Geçersiz bildirim durumu.' }); const user = actor(req); await req.db.run('UPDATE identity_notifications SET status = ?, submitted_at = ?, response_reference = ?, error_code = ?, error_message = ?, retry_count = ?, submitted_by = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?', [status, ['submitted', 'accepted'].includes(status) ? new Date().toISOString() : item.submitted_at, req.body.response_reference || item.response_reference, req.body.error_code || null, req.body.error_message || null, status === 'pending' ? Number(item.retry_count || 0) + 1 : Number(item.retry_count || 0), user.name, item.id]); await audit(req.db, req, 'identity_notification', item.id, 'manual_submission_recorded', item, { status }, req.body.error_message || null); res.json({ success: true, direct_submission: 'BLOCKED_BY_OFFICIAL_CREDENTIALS' }); });
  app.post('/api/reception/shifts/open', async (req, res) => { const existing = await req.db.get("SELECT id FROM cash_shifts WHERE status = 'open'"); if (existing) return res.status(409).json({ error: 'Açık vardiya zaten var.' }); const user = actor(req); const shiftId = id('shift'); await req.db.run("INSERT INTO cash_shifts (id, status, business_date, opening_cash, handover_notes, opened_by) VALUES (?, 'open', ?, ?, ?, ?)", [shiftId, req.body.business_date || today(), Number(req.body.opening_cash || 0), req.body.handover_notes || null, user.name]); await audit(req.db, req, 'cash_shift', shiftId, 'opened', null, req.body); res.status(201).json({ id: shiftId }); });
  // `difference` compares two independently-summed decimal values (opening_cash + a SUM() of
  // payment amounts, vs. the counted closing_cash the shift-closer typed in). Comparing floats
  // with `!== 0` is exact-equality on binary floating point — e.g. 100.10 - 50.05 doesn't land
  // on exactly 50.05, so a shift that's actually balanced to the kuruş could still be flagged as
  // having a difference and block closing without a reason. Round to cents (like the folio
  // balance checks elsewhere in this module) before comparing.
  app.post('/api/reception/shifts/:id/close', async (req, res) => { const shift = await req.db.get("SELECT * FROM cash_shifts WHERE status = 'open' AND id = ?", [req.params.id]); if (!shift) return res.status(404).json({ error: 'Açık vardiya bulunamadı.' }); const closing = Number(req.body.closing_cash); if (!Number.isFinite(closing) || closing < 0) return res.status(400).json({ error: 'Geçerli bir kapanış nakit tutarı girin.' }); const row = await req.db.get("SELECT SUM(p.amount) AS total_amount FROM payments p WHERE p.payment_method = 'cash' AND p.received_at >= ? AND NOT EXISTS (SELECT 1 FROM folio_transactions t JOIN folio_transactions r ON r.folio_id = t.folio_id AND r.transaction_type = 'reversal' AND r.related_reference = 'reversal:' || t.id WHERE t.transaction_type = 'payment' AND t.related_reference = p.id)", [shift.opened_at]); const expected = Number(shift.opening_cash || 0) + Number(row?.total_amount || 0); const difference = Math.round((closing - expected) * 100) / 100; if (difference !== 0 && !req.body.difference_reason) return res.status(400).json({ error: 'Kasa farkı için açıklama zorunludur.' }); const user = actor(req); await req.db.run("UPDATE cash_shifts SET status = 'closed', closed_at = CURRENT_TIMESTAMP, closing_cash = ?, expected_cash = ?, difference_amount = ?, difference_reason = ?, handover_notes = ?, closed_by = ? WHERE id = ?", [closing, expected, difference, req.body.difference_reason || null, req.body.handover_notes || null, user.name, shift.id]); await audit(req.db, req, 'cash_shift', shift.id, 'closed', shift, { closing, expected, difference }); res.json({ success: true, expected_cash: expected, difference }); });
  app.post('/api/reception/night-audit', async (req, res) => { const businessDate = req.body.business_date || today(); const existing = await req.db.get('SELECT * FROM night_audits WHERE business_date = ?', [businessDate]); if (existing?.status === 'completed') return res.json({ success: true, idempotent: true, summary: parse(existing.summary) }); const user = actor(req); const auditId = existing?.id || id('night'); if (!existing) await req.db.run("INSERT INTO night_audits (id, business_date, status) VALUES (?, ?, 'running')", [auditId, businessDate]); const stays = await req.db.all("SELECT * FROM stays WHERE status = 'checked_in'"); let posted = 0; for (const stay of stays) { const marker = `night:${businessDate}:${stay.id}`; const prior = await req.db.get('SELECT id FROM folio_transactions WHERE related_reference = ?', [marker]); if (!prior) { await req.db.run("INSERT INTO folio_transactions (id, folio_id, transaction_type, description, unit_amount, debit, currency, related_reference, created_by) VALUES (?, ?, 'accommodation', 'Geceleme', ?, ?, ?, ?, ?)", [id('ftx'), stay.folio_id, Number(stay.nightly_rate || 0), Number(stay.nightly_rate || 0), stay.currency || 'TRY', marker, user.name]); posted += 1; } } const summary = { business_date: businessDate, posted_accommodation: posted, in_house: stays.length }; await req.db.run("UPDATE night_audits SET status = 'completed', posted_at = CURRENT_TIMESTAMP, posted_by = ?, summary = ? WHERE id = ?", [user.name, json(summary), auditId]); await audit(req.db, req, 'night_audit', auditId, 'completed', null, summary); res.json({ success: true, summary }); });
  app.get('/api/reception/reports', async (req, res) => { const from = req.query.from || today(); const to = req.query.to || from; const reservations = await req.db.all('SELECT status, booking_source, total_amount, arrival_date, departure_date FROM reservations WHERE arrival_date <= ? AND departure_date >= ?', [to, from]); const payments = await req.db.all("SELECT p.amount, p.currency, p.payment_method, p.received_at FROM payments p WHERE p.received_at >= ? AND p.received_at < ? AND NOT EXISTS (SELECT 1 FROM folio_transactions t JOIN folio_transactions r ON r.folio_id = t.folio_id AND r.transaction_type = 'reversal' AND r.related_reference = 'reversal:' || t.id WHERE t.transaction_type = 'payment' AND t.related_reference = p.id)", [`${from}T00:00:00`, `${to}T23:59:59`]); const notifications = await req.db.all('SELECT status, notification_type FROM identity_notifications'); const rooms = await req.db.all('SELECT status FROM rooms'); res.json({ from, to, reservations, payments, notifications, room_status: rooms, summary: { reservations: reservations.length, revenue: reservations.reduce((sum, item) => sum + Number(item.total_amount || 0), 0), payments: payments.reduce((sum, item) => sum + Number(item.amount || 0), 0), occupancy_rooms: rooms.filter(item => item.status === 'occupied').length } }); });
  app.get('/api/reception/audit', async (req, res) => res.json(await req.db.all('SELECT * FROM audit_events ORDER BY created_at DESC LIMIT 500')));
}
